// Connector registry — single source of truth for all connectors TSA supports.
// Dashboard UI, /api/connectors endpoint, and future automation all read from here.
//
// status: 'available'    → Composio auth config set up, user can connect now
// status: 'coming_soon'  → Not yet wired to Composio auth config
//
// comm_channel: true → connector can receive artifact pushes (appears in channel picker)

export const CONNECTOR_REGISTRY = [
  // ── CRM ──────────────────────────────────────────────────────────────────────
  {
    id:          'hubspot',
    name:        'HubSpot',
    category:    'CRM',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull pipeline, deal, and contact data to sharpen sales and revenue diagnostics.',
    data_types:  ['deals', 'contacts', 'companies', 'pipeline_stages'],
    intelligence_use_cases: [
      'Sales conversion rate analysis',
      'Pipeline health and deal velocity',
      'Customer segment profiling',
      'Revenue bottleneck identification',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'salesforce',
    name:        'Salesforce',
    category:    'CRM',
    status:      'available',
    auth_type:   'oauth',
    description: 'Enterprise CRM — pull pipeline, deal stages, lead velocity, and account health.',
    data_types:  ['opportunities', 'leads', 'accounts', 'pipeline_stages'],
    intelligence_use_cases: [
      'Pipeline health and deal velocity',
      'Sales conversion and win rate analysis',
      'Account expansion and churn signals',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'pipedrive',
    name:        'Pipedrive',
    category:    'CRM',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull pipeline health, close rates, and deal age to diagnose sales execution.',
    data_types:  ['deals', 'pipeline_stages', 'activities', 'close_rate'],
    intelligence_use_cases: [
      'Pipeline health and deal velocity',
      'Close rate trend analysis',
      'Sales activity coverage gaps',
    ],
    required_tier: 'intelligence',
  },

  // ── Revenue / Finance ─────────────────────────────────────────────────────────
  {
    id:          'stripe',
    name:        'Stripe',
    category:    'Revenue',
    status:      'available',
    auth_type:   'oauth',
    description: 'Connect revenue, churn, and subscription data for financial health analysis.',
    data_types:  ['mrr', 'churn_rate', 'subscriptions', 'refunds', 'ltv'],
    intelligence_use_cases: [
      'MRR trend and churn analysis',
      'LTV vs CAC health check',
      'Subscription cohort patterns',
      'Revenue concentration risk',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'quickbooks',
    name:        'QuickBooks',
    category:    'Finance',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull P&L, cash flow, outstanding invoices, and burn rate for financial diagnostics.',
    data_types:  ['profit_loss', 'cash_flow', 'invoices', 'burn_rate'],
    intelligence_use_cases: [
      'Cash flow and burn rate monitoring',
      'Invoice aging and collections gap',
      'P&L trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'xero',
    name:        'Xero',
    category:    'Finance',
    status:      'available',
    auth_type:   'oauth',
    description: 'Same as QuickBooks — P&L, cash flow, and invoices for a different accounting user base.',
    data_types:  ['profit_loss', 'cash_flow', 'invoices', 'bank_reconciliation'],
    intelligence_use_cases: [
      'Cash flow and burn rate monitoring',
      'Invoice aging and collections gap',
      'P&L trend analysis',
    ],
    required_tier: 'intelligence',
  },

  // ── Communication ─────────────────────────────────────────────────────────────
  {
    id:           'gmail',
    name:         'Gmail',
    category:     'Comms',
    status:       'available',
    auth_type:    'oauth',
    comm_channel: true,
    description:  'Surface email volume, response patterns, and customer communication signals.',
    data_types:   ['email_volume', 'response_time', 'thread_patterns'],
    intelligence_use_cases: [
      'Customer communication health',
      'Sales follow-up gap detection',
      'Support response time benchmarking',
    ],
    required_tier: 'intelligence',
  },
  {
    id:           'slack',
    name:         'Slack',
    category:     'Comms',
    status:       'available',
    auth_type:    'oauth',
    comm_channel: true,
    description:  'Analyse team communication patterns and operational signal from Slack activity.',
    data_types:   ['channel_activity', 'response_times', 'team_patterns'],
    intelligence_use_cases: [
      'Team velocity and bottleneck signals',
      'Cross-functional communication gaps',
      'Operational noise vs signal ratio',
    ],
    required_tier: 'intelligence',
  },

  // ── Marketing ─────────────────────────────────────────────────────────────────
  {
    id:          'googleanalytics',
    name:        'Google Analytics',
    category:    'Analytics',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull traffic, conversion rate, bounce rate, and source breakdown for growth diagnostics.',
    data_types:  ['sessions', 'conversion_rate', 'bounce_rate', 'traffic_sources'],
    intelligence_use_cases: [
      'Traffic trend and acquisition channel analysis',
      'Conversion funnel gap detection',
      'Audience retention monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'googleads',
    name:        'Google Ads',
    category:    'Marketing',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull spend, CAC, ROAS, and CTR to diagnose paid acquisition performance.',
    data_types:  ['spend', 'cac', 'roas', 'ctr', 'impressions'],
    intelligence_use_cases: [
      'CAC trend and payback period analysis',
      'ROAS by campaign and audience',
      'Ad spend efficiency vs revenue growth',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'metaads',
    name:        'Meta Ads',
    category:    'Marketing',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull Facebook and Instagram ad spend, CAC, ROAS, and CTR for paid social diagnostics.',
    data_types:  ['spend', 'cac', 'roas', 'ctr', 'reach'],
    intelligence_use_cases: [
      'Paid social CAC and ROAS analysis',
      'Audience fatigue and creative performance',
      'Ad spend efficiency vs pipeline',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'mailchimp',
    name:        'Mailchimp',
    category:    'Marketing',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull email open rate, unsubscribe rate, and campaign performance for audience health.',
    data_types:  ['open_rate', 'unsubscribe_rate', 'click_rate', 'list_growth'],
    intelligence_use_cases: [
      'Email list engagement health',
      'Campaign performance benchmarking',
      'Unsubscribe and churn signal detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'klaviyo',
    name:        'Klaviyo',
    category:    'Marketing',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull email and SMS campaign performance, open rates, and revenue attribution.',
    data_types:  ['open_rate', 'revenue_per_email', 'flow_performance', 'list_growth'],
    intelligence_use_cases: [
      'Email-driven revenue analysis',
      'Retention campaign effectiveness',
      'List health and churn signals',
    ],
    required_tier: 'intelligence',
  },

  // ── Docs / Knowledge ──────────────────────────────────────────────────────────
  {
    id:          'googledrive',
    name:        'Google Drive',
    category:    'Docs',
    status:      'available',
    auth_type:   'oauth',
    description: 'Index business documents, SOPs, and playbooks to enrich the intelligence layer.',
    data_types:  ['documents', 'spreadsheets', 'shared_files'],
    intelligence_use_cases: [
      'SOP coverage gap detection',
      'Playbook consistency analysis',
      'Documentation debt surfacing',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'notion',
    name:        'Notion',
    category:    'Docs',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull strategy docs, OKRs, and wikis into the intelligence layer for context.',
    data_types:  ['pages', 'databases', 'okrs'],
    intelligence_use_cases: [
      'Goal alignment between stated OKRs and audit findings',
      'Strategy document vs execution gap',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'confluence',
    name:        'Confluence',
    category:    'Docs',
    status:      'available',
    auth_type:   'oauth',
    description: 'Index team wikis, SOPs, and process documentation to detect coverage gaps.',
    data_types:  ['pages', 'spaces', 'process_docs'],
    intelligence_use_cases: [
      'Process documentation coverage gap',
      'SOP consistency analysis',
      'Knowledge management health',
    ],
    required_tier: 'intelligence',
  },

  // ── Support ───────────────────────────────────────────────────────────────────
  {
    id:          'zendesk',
    name:        'Zendesk',
    category:    'Support',
    status:      'available',
    auth_type:   'api_key',
    description: 'Surface ticket volume, resolution time, and recurring customer issues.',
    data_types:  ['ticket_volume', 'resolution_time', 'csat', 'recurring_issues'],
    intelligence_use_cases: [
      'Support load and team capacity analysis',
      'Recurring issue pattern detection',
      'Customer satisfaction trend monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'intercom',
    name:        'Intercom',
    category:    'Support',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull response time, CSAT, open ticket count, and conversation volume for support health.',
    data_types:  ['response_time', 'csat', 'open_conversations', 'resolution_time'],
    intelligence_use_cases: [
      'Support response time benchmarking',
      'Customer engagement and retention signals',
      'Conversation volume trend analysis',
    ],
    required_tier: 'intelligence',
  },

  // ── HR / People ───────────────────────────────────────────────────────────────
  {
    id:          'gusto',
    name:        'Gusto',
    category:    'HR',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull headcount, payroll burn, and turnover rate for people and cost diagnostics.',
    data_types:  ['headcount', 'payroll_burn', 'turnover_rate'],
    intelligence_use_cases: [
      'Payroll burn vs revenue ratio',
      'Turnover rate and hiring gap detection',
      'Headcount growth vs productivity',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'rippling',
    name:        'Rippling',
    category:    'HR',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull headcount, payroll burn, and turnover rate across departments.',
    data_types:  ['headcount', 'payroll_burn', 'turnover_rate', 'department_breakdown'],
    intelligence_use_cases: [
      'Payroll burn vs revenue ratio',
      'Headcount planning and gap analysis',
      'Turnover pattern detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'bamboohr',
    name:        'BambooHR',
    category:    'HR',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull headcount, turnover rate, and HR data for people health diagnostics.',
    data_types:  ['headcount', 'turnover_rate', 'time_to_hire', 'satisfaction'],
    intelligence_use_cases: [
      'Turnover rate and retention risk',
      'Time-to-hire and recruiting efficiency',
      'Team satisfaction signals',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'deel',
    name:        'Deel',
    category:    'HR',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull contractor headcount and payroll by country for global team cost analysis.',
    data_types:  ['contractor_count', 'payroll_by_country', 'contract_types'],
    intelligence_use_cases: [
      'Global payroll burn analysis',
      'Contractor vs employee cost split',
      'Geographic team distribution risk',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'multiplier',
    name:        'Multiplier',
    category:    'HR',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull international payroll and headcount data for global workforce diagnostics.',
    data_types:  ['headcount', 'payroll_by_country', 'employment_types'],
    intelligence_use_cases: [
      'Global payroll burn analysis',
      'International hiring cost benchmarking',
    ],
    required_tier: 'intelligence',
  },

  // ── Project Management ────────────────────────────────────────────────────────
  {
    id:          'asana',
    name:        'Asana',
    category:    'PM',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull task completion rate, overdue tasks, and project health for execution diagnostics.',
    data_types:  ['task_completion', 'overdue_tasks', 'project_health', 'workload'],
    intelligence_use_cases: [
      'Execution velocity and delivery gap',
      'Overdue task pattern detection',
      'Project health and team capacity',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'monday',
    name:        'Monday',
    category:    'PM',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull task completion, overdue items, and project health across boards.',
    data_types:  ['task_completion', 'overdue_tasks', 'board_health'],
    intelligence_use_cases: [
      'Execution velocity and delivery gap',
      'Cross-team workload imbalance',
      'Project health monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'clickup',
    name:        'ClickUp',
    category:    'PM',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull task completion rate, overdue tasks, and project health from workspaces.',
    data_types:  ['task_completion', 'overdue_tasks', 'sprint_health'],
    intelligence_use_cases: [
      'Delivery velocity and execution gap',
      'Overdue task pattern detection',
      'Sprint health and team capacity',
    ],
    required_tier: 'intelligence',
  },

  // ── Operations ────────────────────────────────────────────────────────────────
  {
    id:          'airtable',
    name:        'Airtable',
    category:    'Ops',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull custom ops data, inventory records, and client tracking for operational diagnostics.',
    data_types:  ['custom_records', 'inventory', 'client_tracking'],
    intelligence_use_cases: [
      'Inventory and fulfilment health',
      'Client delivery tracking',
      'Custom operational metric analysis',
    ],
    required_tier: 'intelligence',
  },

  // ── Engineering ───────────────────────────────────────────────────────────────
  {
    id:          'jira',
    name:        'Jira',
    category:    'Engineering',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull sprint velocity, bug count, and open issues for engineering health diagnostics.',
    data_types:  ['sprint_velocity', 'bug_count', 'open_issues', 'cycle_time'],
    intelligence_use_cases: [
      'Sprint velocity and delivery gap',
      'Bug accumulation and tech debt signals',
      'Engineering throughput analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'linear',
    name:        'Linear',
    category:    'Engineering',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull sprint velocity, open issues, and cycle time for engineering execution analysis.',
    data_types:  ['sprint_velocity', 'open_issues', 'cycle_time', 'priorities'],
    intelligence_use_cases: [
      'Engineering velocity and throughput',
      'Issue backlog health',
      'Priority alignment vs execution',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'github',
    name:        'GitHub',
    category:    'Engineering',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull deployment frequency, PR cycle time, and open bugs for engineering health.',
    data_types:  ['deployment_frequency', 'pr_cycle_time', 'open_issues', 'bug_count'],
    intelligence_use_cases: [
      'Deployment velocity and release cadence',
      'PR review bottleneck detection',
      'Bug accumulation and tech debt signals',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'datadog',
    name:        'Datadog',
    category:    'Engineering',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull error rate, uptime, and incident frequency for system reliability diagnostics.',
    data_types:  ['error_rate', 'uptime', 'incident_count', 'latency'],
    intelligence_use_cases: [
      'System reliability and uptime monitoring',
      'Error rate trend and root cause signals',
      'Incident frequency and MTTR analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'sentry',
    name:        'Sentry',
    category:    'Engineering',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull error rate, incident frequency, and crash data for product reliability diagnostics.',
    data_types:  ['error_rate', 'crash_rate', 'incident_count', 'affected_users'],
    intelligence_use_cases: [
      'Error and crash rate trend analysis',
      'Incident frequency and resolution time',
      'User-impacting bug severity monitoring',
    ],
    required_tier: 'intelligence',
  },

  // ── E-commerce ────────────────────────────────────────────────────────────────
  {
    id:          'shopify',
    name:        'Shopify',
    category:    'Ecommerce',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull GMV, orders, AOV, cart abandonment, and refund rate for commerce health.',
    data_types:  ['gmv', 'orders', 'aov', 'cart_abandonment', 'refund_rate'],
    intelligence_use_cases: [
      'GMV trend and revenue concentration risk',
      'Cart abandonment and conversion gap',
      'Refund rate and fulfilment health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'woocommerce',
    name:        'WooCommerce',
    category:    'Ecommerce',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull GMV, orders, AOV, and cart abandonment for WordPress-based commerce diagnostics.',
    data_types:  ['gmv', 'orders', 'aov', 'cart_abandonment'],
    intelligence_use_cases: [
      'GMV trend and revenue concentration',
      'Cart abandonment and conversion gap',
      'Order volume and fulfilment health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'gorgias',
    name:        'Gorgias',
    category:    'Support',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull support ticket volume tied to orders for ecommerce customer service diagnostics.',
    data_types:  ['ticket_volume', 'response_time', 'resolution_time', 'order_related_tickets'],
    intelligence_use_cases: [
      'Support load tied to order volume',
      'Customer satisfaction and CSAT trend',
      'Ticket type pattern detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'shipstation',
    name:        'ShipStation',
    category:    'Ops',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull fulfilment rate, shipping errors, and delivery time for operations diagnostics.',
    data_types:  ['fulfilment_rate', 'shipping_errors', 'delivery_time', 'carrier_performance'],
    intelligence_use_cases: [
      'Fulfilment rate and shipping gap detection',
      'Delivery time benchmarking',
      'Carrier performance analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'easypost',
    name:        'EasyPost',
    category:    'Ops',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull shipping errors, delivery time, and fulfilment data for logistics diagnostics.',
    data_types:  ['shipping_errors', 'delivery_time', 'tracking_events'],
    intelligence_use_cases: [
      'Shipping error rate and cost impact',
      'Delivery time trend analysis',
      'Carrier performance benchmarking',
    ],
    required_tier: 'intelligence',
  },

  // ── SaaS / Product Analytics ──────────────────────────────────────────────────
  {
    id:          'mixpanel',
    name:        'Mixpanel',
    category:    'Analytics',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull DAU/MAU, activation rate, retention curves, and feature usage for product health.',
    data_types:  ['dau', 'mau', 'activation_rate', 'retention', 'feature_usage'],
    intelligence_use_cases: [
      'User activation and onboarding gap',
      'Retention curve and churn signal',
      'Feature usage and adoption analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'amplitude',
    name:        'Amplitude',
    category:    'Analytics',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull DAU/MAU, activation rate, retention, and feature usage for product diagnostics.',
    data_types:  ['dau', 'mau', 'activation_rate', 'retention_curves', 'conversion_funnels'],
    intelligence_use_cases: [
      'User retention and engagement health',
      'Activation funnel gap detection',
      'Feature adoption and stickiness analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'posthog',
    name:        'PostHog',
    category:    'Analytics',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull DAU/MAU, retention, funnels, and session data for product health diagnostics.',
    data_types:  ['dau', 'mau', 'retention', 'funnels', 'session_recordings'],
    intelligence_use_cases: [
      'Product engagement and retention health',
      'Funnel drop-off and conversion gap',
      'Feature usage and adoption monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'chargebee',
    name:        'Chargebee',
    category:    'Revenue',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull MRR, churn, upgrades/downgrades, and trial conversions for subscription health.',
    data_types:  ['mrr', 'churn_rate', 'upgrades', 'downgrades', 'trial_conversions'],
    intelligence_use_cases: [
      'MRR trend and churn risk analysis',
      'Trial-to-paid conversion monitoring',
      'Upgrade vs downgrade pressure signals',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'recurly',
    name:        'Recurly',
    category:    'Revenue',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull MRR, churn, and subscription metrics for recurring revenue health diagnostics.',
    data_types:  ['mrr', 'churn_rate', 'failed_payments', 'subscription_counts'],
    intelligence_use_cases: [
      'MRR trend and revenue concentration',
      'Churn signal and retention gap',
      'Failed payment and dunning analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'profitwell',
    name:        'ProfitWell',
    category:    'Revenue',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull revenue metrics and churn breakdown for SaaS financial health diagnostics.',
    data_types:  ['mrr', 'churn_rate', 'arpu', 'ltv', 'revenue_breakdown'],
    intelligence_use_cases: [
      'Revenue health and MRR trend',
      'Churn breakdown by segment',
      'LTV and ARPU benchmarking',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'paddle',
    name:        'Paddle',
    category:    'Revenue',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull revenue metrics and churn breakdown for Paddle-managed subscription businesses.',
    data_types:  ['mrr', 'churn_rate', 'refunds', 'subscription_counts'],
    intelligence_use_cases: [
      'Revenue trend and churn risk',
      'Refund rate and pricing signal',
      'Subscription health monitoring',
    ],
    required_tier: 'intelligence',
  },

  // ── Agency / Professional Services ───────────────────────────────────────────
  {
    id:          'harvest',
    name:        'Harvest',
    category:    'Ops',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull billable hours, utilisation rate, and project margin for agency ops diagnostics.',
    data_types:  ['billable_hours', 'utilisation_rate', 'project_margin', 'time_entries'],
    intelligence_use_cases: [
      'Team utilisation and capacity gap',
      'Project margin and profitability analysis',
      'Billable vs non-billable time split',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'toggl',
    name:        'Toggl',
    category:    'Ops',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull billable hours, utilisation rate, and time tracking data for team capacity analysis.',
    data_types:  ['billable_hours', 'utilisation_rate', 'time_by_project', 'time_by_client'],
    intelligence_use_cases: [
      'Team utilisation and capacity health',
      'Billable ratio and revenue leakage',
      'Project time vs budget analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'forecast',
    name:        'Forecast',
    category:    'Ops',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull team capacity vs booked work to detect over/under-allocation before it hits delivery.',
    data_types:  ['team_capacity', 'booked_work', 'utilisation_forecast'],
    intelligence_use_cases: [
      'Team capacity vs pipeline demand',
      'Over-allocation and burnout risk',
      'Resource planning gap detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'clio',
    name:        'Clio',
    category:    'Legal',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull matter pipeline, billable hours, and collections for legal practice diagnostics.',
    data_types:  ['matter_pipeline', 'billable_hours', 'collections', 'wip'],
    intelligence_use_cases: [
      'Collections gap and revenue leakage',
      'Matter pipeline and intake health',
      'Billable hour utilisation analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'mycase',
    name:        'MyCase',
    category:    'Legal',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull matter pipeline, billable hours, and collections for legal practice diagnostics.',
    data_types:  ['matter_pipeline', 'billable_hours', 'collections', 'invoices'],
    intelligence_use_cases: [
      'Collections gap and invoice aging',
      'Matter pipeline and caseload health',
      'Billable efficiency monitoring',
    ],
    required_tier: 'intelligence',
  },

  // ── Healthcare / Wellness ─────────────────────────────────────────────────────
  {
    id:          'simplepractice',
    name:        'SimplePractice',
    category:    'Healthcare',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull appointment fill rate, cancellation rate, and no-shows for practice health.',
    data_types:  ['appointment_fill_rate', 'cancellation_rate', 'no_shows', 'patient_volume'],
    intelligence_use_cases: [
      'Patient flow and capacity utilisation',
      'Cancellation rate and revenue leakage',
      'No-show pattern detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'jane',
    name:        'Jane',
    category:    'Healthcare',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull appointment fill rate, cancellations, and patient flow for clinic diagnostics.',
    data_types:  ['appointment_fill_rate', 'cancellation_rate', 'no_shows', 'waitlist'],
    intelligence_use_cases: [
      'Patient flow and schedule utilisation',
      'Cancellation and no-show trend',
      'Waitlist and capacity gap detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'mindbody',
    name:        'Mindbody',
    category:    'Healthcare',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull class attendance, membership churn, and booking rate for wellness business health.',
    data_types:  ['class_attendance', 'membership_churn', 'booking_rate', 'revenue'],
    intelligence_use_cases: [
      'Membership churn and retention risk',
      'Class fill rate and capacity optimisation',
      'Booking conversion and drop-off analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'practicefusion',
    name:        'Practice Fusion',
    category:    'Healthcare',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull patient volume, billing cycle, and claims status for clinical practice diagnostics.',
    data_types:  ['patient_volume', 'billing_cycle', 'claims_status', 'revenue'],
    intelligence_use_cases: [
      'Patient volume trend and capacity health',
      'Billing cycle and collections gap',
      'Claims status and denial rate monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'kareo',
    name:        'Kareo',
    category:    'Healthcare',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull patient volume, billing, and claims data for medical practice revenue diagnostics.',
    data_types:  ['patient_volume', 'billing_cycle', 'claims_status', 'collections'],
    intelligence_use_cases: [
      'Revenue cycle and collections health',
      'Claims denial rate monitoring',
      'Patient volume and appointment utilisation',
    ],
    required_tier: 'intelligence',
  },

  // ── Construction ──────────────────────────────────────────────────────────────
  {
    id:          'procore',
    name:        'Procore',
    category:    'Construction',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull project progress, cost vs budget, and subcontractor delays for project health.',
    data_types:  ['project_progress', 'cost_vs_budget', 'subcontractor_delays', 'rfi_count'],
    intelligence_use_cases: [
      'Project cost overrun and budget gap',
      'Subcontractor delay and schedule risk',
      'Pipeline and bid win rate analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'buildertrend',
    name:        'Buildertrend',
    category:    'Construction',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull job costing, timeline adherence, and lead pipeline for construction business health.',
    data_types:  ['job_costing', 'timeline_adherence', 'lead_pipeline', 'change_orders'],
    intelligence_use_cases: [
      'Job cost and margin monitoring',
      'Timeline adherence and delay risk',
      'Lead pipeline and bid conversion',
    ],
    required_tier: 'intelligence',
  },

  // ── Hospitality / F&B / Retail ────────────────────────────────────────────────
  {
    id:          'toast',
    name:        'Toast',
    category:    'Hospitality',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull revenue per day, average transaction value, and table turnover for F&B diagnostics.',
    data_types:  ['revenue_per_day', 'avg_transaction', 'table_turnover', 'covers'],
    intelligence_use_cases: [
      'Revenue per cover and table utilisation',
      'Peak vs off-peak performance gap',
      'Average transaction trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'square',
    name:        'Square',
    category:    'Hospitality',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull revenue per day, average transaction, and sales data for retail and F&B diagnostics.',
    data_types:  ['revenue_per_day', 'avg_transaction', 'transaction_count', 'refunds'],
    intelligence_use_cases: [
      'Daily revenue trend and variance',
      'Average transaction and basket size',
      'Refund rate and customer satisfaction signal',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'opentable',
    name:        'OpenTable',
    category:    'Hospitality',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull covers, no-show rate, and reservation fill rate for guest experience diagnostics.',
    data_types:  ['covers', 'no_show_rate', 'reservation_fill_rate', 'guest_ratings'],
    intelligence_use_cases: [
      'Reservation fill rate and capacity health',
      'No-show rate and revenue leakage',
      'Guest rating trend monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'resy',
    name:        'Resy',
    category:    'Hospitality',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull covers, no-show rate, and reservation fill rate for guest experience health.',
    data_types:  ['covers', 'no_show_rate', 'reservation_fill_rate', 'waitlist'],
    intelligence_use_cases: [
      'Reservation and capacity utilisation',
      'No-show rate and revenue impact',
      'Waitlist demand signal analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'lightspeed',
    name:        'Lightspeed',
    category:    'Hospitality',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull inventory turnover and sales per SKU for retail and hospitality operations.',
    data_types:  ['inventory_turnover', 'sales_per_sku', 'shrinkage', 'stock_levels'],
    intelligence_use_cases: [
      'Inventory turnover and dead stock detection',
      'Sales per SKU and margin analysis',
      'Stock-out and overstock risk monitoring',
    ],
    required_tier: 'intelligence',
  },

  // ── Real Estate ───────────────────────────────────────────────────────────────
  {
    id:          'buildium',
    name:        'Buildium',
    category:    'Real Estate',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull occupancy rate, rent collected vs owed, and maintenance backlog for portfolio health.',
    data_types:  ['occupancy_rate', 'rent_collected', 'rent_owed', 'maintenance_backlog'],
    intelligence_use_cases: [
      'Occupancy rate and vacancy risk',
      'Rent collection gap and delinquency',
      'Maintenance backlog and cost monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'appfolio',
    name:        'AppFolio',
    category:    'Real Estate',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull occupancy rate, rent collected, and maintenance backlog for property management health.',
    data_types:  ['occupancy_rate', 'rent_collected', 'maintenance_backlog', 'lease_renewals'],
    intelligence_use_cases: [
      'Occupancy and vacancy risk analysis',
      'Rent delinquency and collection gap',
      'Maintenance cost and backlog monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'yardi',
    name:        'Yardi',
    category:    'Real Estate',
    status:      'available',
    auth_type:   'oauth',
    description: 'Enterprise property management — pull occupancy, collections, and portfolio health at scale.',
    data_types:  ['occupancy_rate', 'rent_collected', 'portfolio_performance', 'maintenance_backlog'],
    intelligence_use_cases: [
      'Portfolio occupancy and vacancy trend',
      'Rent collection and delinquency rate',
      'Maintenance cost and capital expenditure',
    ],
    required_tier: 'intelligence',
  },

  // ── Logistics & Freight ───────────────────────────────────────────────────────
  {
    id:          'samsara',
    name:        'Samsara',
    category:    'Logistics',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull fleet utilisation, idle time, and driver performance for logistics diagnostics.',
    data_types:  ['fleet_utilisation', 'idle_time', 'driver_performance', 'fuel_efficiency'],
    intelligence_use_cases: [
      'Fleet utilisation and capacity analysis',
      'Driver performance and safety monitoring',
      'Idle time and fuel cost optimisation',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'verizonconnect',
    name:        'Verizon Connect',
    category:    'Logistics',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull fleet utilisation, idle time, and driver performance for fleet operations health.',
    data_types:  ['fleet_utilisation', 'idle_time', 'driver_performance', 'route_efficiency'],
    intelligence_use_cases: [
      'Fleet utilisation and route efficiency',
      'Driver performance benchmarking',
      'Idle time and operational cost analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'freightpop',
    name:        'FreightPOP',
    category:    'Logistics',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull on-time delivery rate and freight cost per shipment for logistics cost diagnostics.',
    data_types:  ['on_time_delivery', 'freight_cost_per_shipment', 'carrier_performance'],
    intelligence_use_cases: [
      'On-time delivery rate and delay risk',
      'Freight cost benchmarking by carrier',
      'Shipment volume and cost trend',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'shipwell',
    name:        'Shipwell',
    category:    'Logistics',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull on-time delivery rate and freight cost per shipment for supply chain diagnostics.',
    data_types:  ['on_time_delivery', 'freight_cost', 'carrier_performance', 'exception_rate'],
    intelligence_use_cases: [
      'On-time delivery and carrier performance',
      'Freight cost optimisation signals',
      'Shipment exception rate monitoring',
    ],
    required_tier: 'intelligence',
  },
  // ── Fintech / Finance / Insurance ────────────────────────────────────────────
  {
    id:          'plaid',
    name:        'Plaid',
    category:    'Fintech',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull bank balance, cash flow, and transaction categorisation for financial health.',
    data_types:  ['bank_balance', 'cash_flow', 'transactions', 'categorisation'],
    intelligence_use_cases: [
      'Cash flow and burn rate monitoring',
      'Transaction categorisation and spend analysis',
      'Bank balance and runway tracking',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'experian',
    name:        'Experian',
    category:    'Fintech',
    status:      'available',
    auth_type:   'api_key',
    description: 'Pull credit risk data for collections, credit exposure, and compliance monitoring.',
    data_types:  ['credit_score', 'credit_risk', 'delinquency_signals'],
    intelligence_use_cases: [
      'Credit risk and collections exposure',
      'Customer delinquency signal detection',
      'Risk & compliance monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'equifax',
    name:        'Equifax',
    category:    'Fintech',
    status:      'available',
    auth_type:   'api_key',
    description: 'Pull credit risk and verification data for collections and compliance diagnostics.',
    data_types:  ['credit_risk', 'identity_verification', 'delinquency_signals'],
    intelligence_use_cases: [
      'Credit risk and collections gap',
      'Identity verification and fraud signals',
      'Compliance and risk monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'guidewire',
    name:        'Guidewire',
    category:    'Insurance',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull claims processing, loss ratio, and cycle time for insurance operations health.',
    data_types:  ['claims_processing', 'loss_ratio', 'cycle_time', 'policy_count'],
    intelligence_use_cases: [
      'Claims cycle time and bottleneck detection',
      'Loss ratio trend and profitability analysis',
      'Claims processing efficiency monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'duckcreek',
    name:        'Duck Creek',
    category:    'Insurance',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull claims processing, loss ratio, and cycle time for insurance operations diagnostics.',
    data_types:  ['claims_processing', 'loss_ratio', 'cycle_time', 'underwriting_data'],
    intelligence_use_cases: [
      'Claims cycle time and processing efficiency',
      'Loss ratio trend analysis',
      'Underwriting and risk exposure monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'netsuite',
    name:        'NetSuite',
    category:    'Finance',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull operations costs, billing, and compliance tracking for enterprise finance diagnostics.',
    data_types:  ['operations_costs', 'billing', 'compliance', 'financial_statements'],
    intelligence_use_cases: [
      'Operations cost and margin analysis',
      'Billing cycle and collections health',
      'Compliance tracking and audit readiness',
    ],
    required_tier: 'intelligence',
  },

  // ── Media / Creator / Education ───────────────────────────────────────────────
  {
    id:          'youtubeanalytics',
    name:        'YouTube Analytics',
    category:    'Media',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull views, watch time, subscriber growth, and drop-off for audience health.',
    data_types:  ['views', 'watch_time', 'subscriber_growth', 'drop_off_rate'],
    intelligence_use_cases: [
      'Audience growth and retention analysis',
      'Watch time and engagement trend',
      'Content drop-off and hook performance',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'spotify',
    name:        'Spotify',
    category:    'Media',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull streams, listener growth, and drop-off for podcast and music audience diagnostics.',
    data_types:  ['streams', 'listeners', 'subscriber_growth', 'completion_rate'],
    intelligence_use_cases: [
      'Audience growth and listener retention',
      'Episode completion and drop-off rate',
      'Listener engagement trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'podbean',
    name:        'Podbean',
    category:    'Media',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull downloads, listener growth, and episode performance for podcast health diagnostics.',
    data_types:  ['downloads', 'listeners', 'episode_performance', 'subscriber_growth'],
    intelligence_use_cases: [
      'Listener growth and episode performance',
      'Download trend and audience retention',
      'Monetisation and subscriber health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'teachable',
    name:        'Teachable',
    category:    'Education',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull enrolment, completion rate, and churn for online course business diagnostics.',
    data_types:  ['enrolments', 'completion_rate', 'churn', 'revenue'],
    intelligence_use_cases: [
      'Course enrolment and growth trend',
      'Completion rate and student retention',
      'Churn signal and re-engagement gap',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'kajabi',
    name:        'Kajabi',
    category:    'Education',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull enrolment, completion rate, and churn for creator business health diagnostics.',
    data_types:  ['enrolments', 'completion_rate', 'churn', 'mrr'],
    intelligence_use_cases: [
      'Student enrolment and retention health',
      'Completion rate and drop-off analysis',
      'MRR trend and subscription health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'thinkific',
    name:        'Thinkific',
    category:    'Education',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull enrolment, completion rate, and student churn for online learning diagnostics.',
    data_types:  ['enrolments', 'completion_rate', 'churn', 'revenue'],
    intelligence_use_cases: [
      'Course enrolment and growth analysis',
      'Student completion and retention rate',
      'Revenue trend and pricing health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'patreon',
    name:        'Patreon',
    category:    'Media',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull subscriber count, MRR, and churn for creator monetisation diagnostics.',
    data_types:  ['subscriber_count', 'mrr', 'churn_rate', 'patron_growth'],
    intelligence_use_cases: [
      'Subscriber growth and churn risk',
      'MRR trend and monetisation health',
      'Patron retention and tier performance',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'substack',
    name:        'Substack',
    category:    'Media',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull subscriber count, MRR, and churn for newsletter monetisation diagnostics.',
    data_types:  ['subscriber_count', 'paid_subscribers', 'mrr', 'churn_rate', 'open_rate'],
    intelligence_use_cases: [
      'Subscriber growth and paid conversion',
      'Churn risk and retention signals',
      'MRR trend and monetisation health',
    ],
    required_tier: 'intelligence',
  },

  // ── Energy & Utilities / Telecoms ─────────────────────────────────────────────
  {
    id:          'salesforceenergy',
    name:        'Salesforce Energy Cloud',
    category:    'Energy',
    status:      'available',
    auth_type:   'oauth',
    description: 'Pull customer accounts, billing health, and churn signals for utilities and telecoms.',
    data_types:  ['customer_accounts', 'billing_health', 'churn_signals', 'service_requests'],
    intelligence_use_cases: [
      'Customer billing health and churn risk',
      'Service request volume and resolution',
      'Subscriber retention and revenue trend',
    ],
    required_tier: 'intelligence',
  },
]

// Returns the full registry
export function getConnectorRegistry() {
  return CONNECTOR_REGISTRY
}

// Returns only connectors with status === 'available'
export function getAvailableConnectors() {
  return CONNECTOR_REGISTRY.filter(c => c.status === 'available')
}

// Returns connector IDs that can be used as communication push channels
export function getCommChannelProviders() {
  return CONNECTOR_REGISTRY.filter(c => c.comm_channel === true).map(c => c.id)
}

// Returns a single connector definition by id, or null
export function getConnectorDefinition(id) {
  return CONNECTOR_REGISTRY.find(c => c.id === id) ?? null
}
