// Connector registry — single source of truth for all connectors TSA supports.
// Dashboard UI, /api/connectors endpoint, and future automation all read from here.
//
// comm_channel: true → connector can receive artifact pushes (appears in channel picker)

export const CONNECTOR_REGISTRY = [
  // ── CRM ──────────────────────────────────────────────────────────────────────
  {
    id:          'hubspot',
    name:        'HubSpot',
    category:    'CRM',
    status:      'available',
    semantic_status: 'verified',
    auth_type:   'oauth',
    description: 'Pull pipeline, deal, and contact data to sharpen sales and revenue diagnostics.',
    data_types:  ['deals', 'contacts', 'companies', 'pipeline_stages'],
    intelligence_use_cases: [
      'Sales conversion rate analysis',
      'Pipeline health and deal velocity',
      'Customer segment profiling',
      'Revenue bottleneck identification',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'salesforce',
    name:        'Salesforce',
    category:    'CRM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Enterprise CRM — pull pipeline, deal stages, lead velocity, and account health.',
    data_types:  ['opportunities', 'leads', 'accounts', 'pipeline_stages'],
    intelligence_use_cases: [
      'Pipeline health and deal velocity',
      'Sales conversion and win rate analysis',
      'Account expansion and churn signals',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'pipedrive',
    name:        'Pipedrive',
    category:    'CRM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull pipeline health, close rates, and deal age to diagnose sales execution.',
    data_types:  ['deals', 'pipeline_stages', 'activities', 'close_rate'],
    intelligence_use_cases: [
      'Pipeline health and deal velocity',
      'Close rate trend analysis',
      'Sales activity coverage gaps',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'zohocrm',
    name:        'Zoho CRM',
    category:    'CRM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull pipeline, deal stages, and contact data from Zoho CRM for sales health diagnostics.',
    data_types:  ['deals', 'contacts', 'pipeline_stages', 'leads', 'close_rate'],
    intelligence_use_cases: [
      'Pipeline health and deal velocity',
      'Sales conversion and win rate analysis',
      'Lead funnel and contact growth trend',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'zohobigin',
    name:        'Zoho Bigin',
    category:    'CRM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Lightweight CRM — pull pipeline and deal data for small business sales diagnostics.',
    data_types:  ['deals', 'pipeline_stages', 'contacts', 'activities'],
    intelligence_use_cases: [
      'Pipeline health and deal velocity',
      'Sales activity and follow-up gap detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'dynamics365',
    name:        'Dynamics 365',
    category:    'CRM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull pipeline, deal stages, and account health from Microsoft Dynamics for sales diagnostics.',
    data_types:  ['opportunities', 'pipeline_stages', 'accounts', 'lead_velocity'],
    intelligence_use_cases: [
      'Pipeline health and deal velocity',
      'Sales conversion and win rate analysis',
      'Account expansion and churn signals',
    ],
    required_tier: 'intelligence',
  },

  // ── Revenue / Billing ─────────────────────────────────────────────────────────
  {
    id:          'stripe',
    name:        'Stripe',
    category:    'Revenue',
    status:      'available',
    semantic_status: 'verified',
    auth_type:   'oauth',
    description: 'Connect revenue, churn, and subscription data for financial health analysis.',
    data_types:  ['mrr', 'churn_rate', 'subscriptions', 'refunds', 'ltv'],
    intelligence_use_cases: [
      'MRR trend and churn analysis',
      'LTV vs CAC health check',
      'Subscription cohort patterns',
      'Revenue concentration risk',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'maxio',
    name:        'Maxio',
    category:    'Revenue',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull MRR, churn, upgrades/downgrades, and trial conversions for subscription health.',
    data_types:  ['mrr', 'churn_rate', 'upgrades', 'downgrades', 'trial_conversions'],
    intelligence_use_cases: [
      'MRR trend and churn risk analysis',
      'Trial-to-paid conversion monitoring',
      'Upgrade vs downgrade pressure signals',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'freshbooks',
    name:        'FreshBooks',
    category:    'Revenue',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull invoices, revenue, and outstanding payments for cash flow and billing diagnostics.',
    data_types:  ['invoices', 'revenue', 'outstanding_payments', 'expenses'],
    intelligence_use_cases: [
      'Invoice aging and collections gap',
      'Cash flow and burn rate monitoring',
      'Revenue trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'zohoinvoice',
    name:        'Zoho Invoice',
    category:    'Revenue',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull invoice status, payment timelines, and outstanding amounts for billing health.',
    data_types:  ['invoices', 'outstanding_payments', 'payment_cycles'],
    intelligence_use_cases: [
      'Invoice aging and collections gap',
      'Payment cycle health',
      'Overdue invoice pattern detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'taxjar',
    name:        'TaxJar',
    category:    'Revenue',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull tax compliance data and sales tax obligations for financial risk diagnostics.',
    data_types:  ['tax_obligations', 'nexus_status', 'sales_tax_collected'],
    intelligence_use_cases: [
      'Tax compliance risk monitoring',
      'Multi-state nexus exposure analysis',
      'Sales tax liability trend',
    ],
    required_tier: 'intelligence',
  },

  // ── Finance / Accounting ──────────────────────────────────────────────────────
  {
    id:          'zohbooks',
    name:        'Zoho Books',
    category:    'Finance',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull P&L, cash flow, invoices, and bank reconciliation for financial health diagnostics.',
    data_types:  ['profit_loss', 'cash_flow', 'invoices', 'bank_reconciliation', 'expenses'],
    intelligence_use_cases: [
      'Cash flow and burn rate monitoring',
      'Invoice aging and collections gap',
      'P&L trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'quickbooks',
    name:        'QuickBooks',
    category:    'Finance',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull P&L, cash flow, outstanding invoices, and burn rate for financial diagnostics.',
    data_types:  ['profit_loss', 'cash_flow', 'invoices', 'burn_rate'],
    intelligence_use_cases: [
      'Cash flow and burn rate monitoring',
      'Invoice aging and collections gap',
      'P&L trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'xero',
    name:        'Xero',
    category:    'Finance',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull P&L, cash flow, and invoices for a cloud-first accounting user base.',
    data_types:  ['profit_loss', 'cash_flow', 'invoices', 'bank_reconciliation'],
    intelligence_use_cases: [
      'Cash flow and burn rate monitoring',
      'Invoice aging and collections gap',
      'P&L trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'netsuite',
    name:        'NetSuite',
    category:    'Finance',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull operations costs, billing, and compliance tracking for enterprise finance diagnostics.',
    data_types:  ['operations_costs', 'billing', 'compliance', 'financial_statements'],
    intelligence_use_cases: [
      'Operations cost and margin analysis',
      'Billing cycle and collections health',
      'Compliance tracking and audit readiness',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'brex',
    name:        'Brex',
    category:    'Finance',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull spend data, card transactions, and budget utilisation for financial ops diagnostics.',
    data_types:  ['spend', 'card_transactions', 'budget_utilisation', 'expense_categories'],
    intelligence_use_cases: [
      'Spend trend and budget variance',
      'Department-level expense analysis',
      'Burn rate and runway monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'ramp',
    name:        'Ramp',
    category:    'Finance',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull spend data and savings insights for financial efficiency and cost control diagnostics.',
    data_types:  ['spend', 'savings_identified', 'budget_utilisation', 'vendor_breakdown'],
    intelligence_use_cases: [
      'Spend efficiency and cost reduction signals',
      'Vendor concentration risk',
      'Budget utilisation and variance',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'coupa',
    name:        'Coupa',
    category:    'Finance',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull procurement spend, supplier performance, and purchase orders for ops cost diagnostics.',
    data_types:  ['procurement_spend', 'supplier_performance', 'purchase_orders'],
    intelligence_use_cases: [
      'Procurement spend and cost control',
      'Supplier concentration risk',
      'Purchase order cycle time analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'bench',
    name:        'Bench',
    category:    'Finance',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull bookkeeping data, P&L, and cash flow summaries for financial health diagnostics.',
    data_types:  ['profit_loss', 'cash_flow', 'expense_categories', 'monthly_reports'],
    intelligence_use_cases: [
      'P&L trend and margin analysis',
      'Cash flow and burn rate monitoring',
      'Expense category and cost structure health',
    ],
    required_tier: 'intelligence',
  },

  // ── Communication ─────────────────────────────────────────────────────────────
  {
    id:           'gmail',
    name:         'Gmail',
    category:     'Comms',
    status:       'available',
    semantic_status: 'transport-only',
    auth_type:    'oauth',
    comm_channel: true,
    description:  'Surface email volume, response patterns, and customer communication signals.',
    data_types:   ['email_volume', 'response_time', 'thread_patterns'],
    intelligence_use_cases: [
      'Customer communication health',
      'Sales follow-up gap detection',
      'Support response time benchmarking',
    ],
    required_tier: 'intelligence',
  },
  {
    id:           'slack',
    name:         'Slack',
    category:     'Comms',
    status:       'available',
    semantic_status: 'transport-only',
    auth_type:    'oauth',
    comm_channel: true,
    description:  'Analyse team communication patterns and operational signal from Slack activity.',
    data_types:   ['channel_activity', 'response_times', 'team_patterns'],
    intelligence_use_cases: [
      'Team velocity and bottleneck signals',
      'Cross-functional communication gaps',
      'Operational noise vs signal ratio',
    ],
    required_tier: 'intelligence',
  },
  {
    id:           'outlook',
    name:         'Outlook',
    category:     'Comms',
    status:       'available',
    semantic_status: 'transport-only',
    auth_type:    'oauth',
    comm_channel: true,
    description:  'Surface email volume, response patterns, and communication health from Outlook.',
    data_types:   ['email_volume', 'response_time', 'thread_patterns'],
    intelligence_use_cases: [
      'Customer communication health',
      'Sales follow-up gap detection',
      'Response time benchmarking',
    ],
    required_tier: 'intelligence',
  },
  {
    id:           'teams',
    name:         'Microsoft Teams',
    category:     'Comms',
    status:       'available',
    semantic_status: 'transport-only',
    auth_type:    'oauth',
    comm_channel: true,
    description:  'Analyse team communication patterns and collaboration signal from Teams activity.',
    data_types:   ['channel_activity', 'response_times', 'meeting_load', 'team_patterns'],
    intelligence_use_cases: [
      'Team velocity and communication bottleneck',
      'Meeting load vs deep-work ratio',
      'Cross-functional collaboration gaps',
    ],
    required_tier: 'intelligence',
  },
  {
    id:           'whatsapp',
    name:         'WhatsApp Business',
    category:     'Comms',
    status:       'available',
    semantic_status: 'transport-only',
    auth_type:    'oauth',
    comm_channel: true,
    description:  'Send artifacts and action plans directly to WhatsApp Business for instant delivery.',
    data_types:   ['messages', 'notifications'],
    intelligence_use_cases: [
      'Instant artifact delivery to WhatsApp',
      'Action plan push notifications',
    ],
    required_tier: 'intelligence',
  },
  {
    id:           'telegram',
    name:         'Telegram',
    category:     'Comms',
    status:       'available',
    semantic_status: 'transport-only',
    auth_type:    'oauth',
    comm_channel: true,
    description:  'Send artifacts and action plans directly to a Telegram chat or channel.',
    data_types:   ['messages', 'notifications'],
    intelligence_use_cases: [
      'Instant artifact delivery to Telegram',
      'Action plan push notifications',
    ],
    required_tier: 'intelligence',
  },
  {
    id:           'zohomail',
    name:         'Zoho Mail',
    category:     'Comms',
    status:       'available',
    semantic_status: 'transport-only',
    auth_type:    'oauth',
    description:  'Surface email volume, response patterns, and communication health from Zoho Mail.',
    data_types:   ['email_volume', 'response_time', 'thread_patterns'],
    intelligence_use_cases: [
      'Customer communication health',
      'Sales follow-up gap detection',
      'Response time benchmarking',
    ],
    required_tier: 'intelligence',
  },
  {
    id:           'discord',
    name:         'Discord',
    category:     'Comms',
    status:       'available',
    semantic_status: 'transport-only',
    auth_type:    'oauth',
    description:  'Surface community engagement and send operational updates to Discord servers.',
    data_types:   ['server_activity', 'member_growth', 'channel_engagement'],
    intelligence_use_cases: [
      'Community growth and engagement health',
      'Channel activity and member retention signals',
    ],
    required_tier: 'intelligence',
  },

  // ── Marketing ─────────────────────────────────────────────────────────────────
  {
    id:          'googleanalytics',
    name:        'Google Analytics',
    category:    'Analytics',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull traffic, conversion rate, bounce rate, and source breakdown for growth diagnostics.',
    data_types:  ['sessions', 'conversion_rate', 'bounce_rate', 'traffic_sources'],
    intelligence_use_cases: [
      'Traffic trend and acquisition channel analysis',
      'Conversion funnel gap detection',
      'Audience retention monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'googleads',
    name:        'Google Ads',
    category:    'Marketing',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull spend, CAC, ROAS, and CTR to diagnose paid acquisition performance.',
    data_types:  ['spend', 'cac', 'roas', 'ctr', 'impressions'],
    intelligence_use_cases: [
      'CAC trend and payback period analysis',
      'ROAS by campaign and audience',
      'Ad spend efficiency vs revenue growth',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'metaads',
    name:        'Meta Ads',
    category:    'Marketing',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull Facebook and Instagram ad spend, CAC, ROAS, and CTR for paid social diagnostics.',
    data_types:  ['spend', 'cac', 'roas', 'ctr', 'reach'],
    intelligence_use_cases: [
      'Paid social CAC and ROAS analysis',
      'Audience fatigue and creative performance',
      'Ad spend efficiency vs pipeline',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'mailchimp',
    name:        'Mailchimp',
    category:    'Marketing',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull email open rate, unsubscribe rate, and campaign performance for audience health.',
    data_types:  ['open_rate', 'unsubscribe_rate', 'click_rate', 'list_growth'],
    intelligence_use_cases: [
      'Email list engagement health',
      'Campaign performance benchmarking',
      'Unsubscribe and churn signal detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'klaviyo',
    name:        'Klaviyo',
    category:    'Marketing',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull email and SMS campaign performance, open rates, and revenue attribution.',
    data_types:  ['open_rate', 'revenue_per_email', 'flow_performance', 'list_growth'],
    intelligence_use_cases: [
      'Email-driven revenue analysis',
      'Retention campaign effectiveness',
      'List health and churn signals',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'mailerlite',
    name:        'MailerLite',
    category:    'Marketing',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull newsletter open rate, click rate, and subscriber growth for email health.',
    data_types:  ['open_rate', 'click_rate', 'subscriber_growth', 'unsubscribe_rate'],
    intelligence_use_cases: [
      'Email engagement and list health',
      'Newsletter growth and churn signals',
      'Campaign performance benchmarking',
    ],
    required_tier: 'intelligence',
  },

  // ── Docs / Knowledge ──────────────────────────────────────────────────────────
  {
    id:          'googledrive',
    name:        'Google Drive',
    category:    'Docs',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Index business documents, SOPs, and playbooks to enrich the intelligence layer.',
    data_types:  ['documents', 'spreadsheets', 'shared_files'],
    intelligence_use_cases: [
      'SOP coverage gap detection',
      'Playbook consistency analysis',
      'Documentation debt surfacing',
    ],
    required_tier: 'intelligence',
  },
  {
    id:           'notion',
    name:         'Notion',
    category:     'Docs',
    status:       'available',
    semantic_status: 'transport-only',
    auth_type:    'oauth',
    comm_channel: true,
    description:  'Pull strategy docs, OKRs, and wikis into the intelligence layer for context.',
    data_types:  ['pages', 'databases', 'okrs'],
    intelligence_use_cases: [
      'Goal alignment between stated OKRs and audit findings',
      'Strategy document vs execution gap',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'confluence',
    name:        'Confluence',
    category:    'Docs',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Index team wikis, SOPs, and process documentation to detect coverage gaps.',
    data_types:  ['pages', 'spaces', 'process_docs'],
    intelligence_use_cases: [
      'Process documentation coverage gap',
      'SOP consistency analysis',
      'Knowledge management health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'sharepoint',
    name:        'SharePoint',
    category:    'Docs',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Index business documents, SOPs, and wikis from SharePoint to enrich the intelligence layer.',
    data_types:  ['documents', 'wikis', 'process_docs', 'shared_files'],
    intelligence_use_cases: [
      'SOP and process documentation coverage',
      'Knowledge management health',
      'Documentation gap detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'onedrive',
    name:        'OneDrive',
    category:    'Docs',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Index business files and documents from OneDrive to enrich the intelligence layer.',
    data_types:  ['documents', 'spreadsheets', 'shared_files'],
    intelligence_use_cases: [
      'Document coverage and gap detection',
      'Playbook and SOP consistency analysis',
      'File sharing and collaboration health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'egnyte',
    name:        'Egnyte',
    category:    'Docs',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Index enterprise files, project documents, and compliance content from Egnyte.',
    data_types:  ['documents', 'project_files', 'compliance_docs', 'shared_files'],
    intelligence_use_cases: [
      'Compliance document coverage',
      'Project file organisation health',
      'Documentation gap and SOP analysis',
    ],
    required_tier: 'intelligence',
  },

  // ── Support ───────────────────────────────────────────────────────────────────
  {
    id:          'zohodesk',
    name:        'Zoho Desk',
    category:    'Support',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull ticket volume, resolution time, and CSAT for customer support health diagnostics.',
    data_types:  ['ticket_volume', 'resolution_time', 'csat', 'first_response_time'],
    intelligence_use_cases: [
      'Support load and capacity analysis',
      'Resolution time and CSAT trend',
      'Recurring issue pattern detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'freshdesk',
    name:        'Freshdesk',
    category:    'Support',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull ticket volume, resolution time, and CSAT for helpdesk health diagnostics.',
    data_types:  ['ticket_volume', 'resolution_time', 'csat', 'first_response_time'],
    intelligence_use_cases: [
      'Support load and team capacity analysis',
      'Resolution time benchmarking',
      'Customer satisfaction trend monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'zendesk',
    name:        'Zendesk',
    category:    'Support',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'api_key',
    description: 'Surface ticket volume, resolution time, and recurring customer issues.',
    data_types:  ['ticket_volume', 'resolution_time', 'csat', 'recurring_issues'],
    intelligence_use_cases: [
      'Support load and team capacity analysis',
      'Recurring issue pattern detection',
      'Customer satisfaction trend monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'intercom',
    name:        'Intercom',
    category:    'Support',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull response time, CSAT, open ticket count, and conversation volume for support health.',
    data_types:  ['response_time', 'csat', 'open_conversations', 'resolution_time'],
    intelligence_use_cases: [
      'Support response time benchmarking',
      'Customer engagement and retention signals',
      'Conversation volume trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'gorgias',
    name:        'Gorgias',
    category:    'Support',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull support ticket volume tied to orders for ecommerce customer service diagnostics.',
    data_types:  ['ticket_volume', 'response_time', 'resolution_time', 'order_related_tickets'],
    intelligence_use_cases: [
      'Support load tied to order volume',
      'Customer satisfaction and CSAT trend',
      'Ticket type pattern detection',
    ],
    required_tier: 'intelligence',
  },

  // ── HR / People ───────────────────────────────────────────────────────────────
  {
    id:          'gusto',
    name:        'Gusto',
    category:    'HR',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull headcount, payroll burn, and turnover rate for people and cost diagnostics.',
    data_types:  ['headcount', 'payroll_burn', 'turnover_rate'],
    intelligence_use_cases: [
      'Payroll burn vs revenue ratio',
      'Turnover rate and hiring gap detection',
      'Headcount growth vs productivity',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'bamboohr',
    name:        'BambooHR',
    category:    'HR',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull headcount, turnover rate, and HR data for people health diagnostics.',
    data_types:  ['headcount', 'turnover_rate', 'time_to_hire', 'satisfaction'],
    intelligence_use_cases: [
      'Turnover rate and retention risk',
      'Time-to-hire and recruiting efficiency',
      'Team satisfaction signals',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'workday',
    name:        'Workday',
    category:    'HR',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull headcount, payroll, and workforce planning data for enterprise HR diagnostics.',
    data_types:  ['headcount', 'payroll_burn', 'turnover_rate', 'workforce_planning'],
    intelligence_use_cases: [
      'Payroll burn vs revenue ratio',
      'Turnover pattern and retention risk',
      'Headcount vs growth plan alignment',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'greenhouse',
    name:        'Greenhouse',
    category:    'HR',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull open roles, time-to-fill, and hiring funnel data for recruiting health diagnostics.',
    data_types:  ['open_roles', 'time_to_fill', 'hiring_funnel', 'offer_acceptance_rate'],
    intelligence_use_cases: [
      'Hiring funnel and time-to-fill analysis',
      'Offer acceptance rate and talent signals',
      'Recruiting pipeline health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'lever',
    name:        'Lever',
    category:    'HR',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull open roles, pipeline stage data, and offer conversion for recruiting diagnostics.',
    data_types:  ['open_roles', 'pipeline_stages', 'time_to_hire', 'offer_conversion'],
    intelligence_use_cases: [
      'Recruiting pipeline and velocity analysis',
      'Stage-level conversion and bottleneck',
      'Time-to-hire benchmarking',
    ],
    required_tier: 'intelligence',
  },

  // ── Project Management ────────────────────────────────────────────────────────
  {
    id:          'asana',
    name:        'Asana',
    category:    'PM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull task completion rate, overdue tasks, and project health for execution diagnostics.',
    data_types:  ['task_completion', 'overdue_tasks', 'project_health', 'workload'],
    intelligence_use_cases: [
      'Execution velocity and delivery gap',
      'Overdue task pattern detection',
      'Project health and team capacity',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'monday',
    name:        'Monday',
    category:    'PM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull task completion, overdue items, and project health across boards.',
    data_types:  ['task_completion', 'overdue_tasks', 'board_health'],
    intelligence_use_cases: [
      'Execution velocity and delivery gap',
      'Cross-team workload imbalance',
      'Project health monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'clickup',
    name:        'ClickUp',
    category:    'PM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull task completion rate, overdue tasks, and project health from workspaces.',
    data_types:  ['task_completion', 'overdue_tasks', 'sprint_health'],
    intelligence_use_cases: [
      'Delivery velocity and execution gap',
      'Overdue task pattern detection',
      'Sprint health and team capacity',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'basecamp',
    name:        'Basecamp',
    category:    'PM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull project status, to-dos, and team activity for delivery health diagnostics.',
    data_types:  ['project_status', 'todos', 'team_activity', 'overdue_items'],
    intelligence_use_cases: [
      'Project delivery and execution health',
      'Team engagement and activity signals',
      'Overdue item and velocity analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'wrike',
    name:        'Wrike',
    category:    'PM',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull task completion, project timelines, and workload for execution diagnostics.',
    data_types:  ['task_completion', 'project_timelines', 'workload', 'overdue_tasks'],
    intelligence_use_cases: [
      'Execution velocity and delivery gap',
      'Workload distribution and capacity health',
      'Project timeline adherence analysis',
    ],
    required_tier: 'intelligence',
  },

  // ── Operations ────────────────────────────────────────────────────────────────
  {
    id:          'airtable',
    name:        'Airtable',
    category:    'Ops',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull custom ops data, inventory records, and client tracking for operational diagnostics.',
    data_types:  ['custom_records', 'inventory', 'client_tracking'],
    intelligence_use_cases: [
      'Inventory and fulfilment health',
      'Client delivery tracking',
      'Custom operational metric analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'harvest',
    name:        'Harvest',
    category:    'Ops',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull billable hours, utilisation rate, and project margin for agency ops diagnostics.',
    data_types:  ['billable_hours', 'utilisation_rate', 'project_margin', 'time_entries'],
    intelligence_use_cases: [
      'Team utilisation and capacity gap',
      'Project margin and profitability analysis',
      'Billable vs non-billable time split',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'toggl',
    name:        'Toggl',
    category:    'Ops',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull billable hours, utilisation rate, and time tracking data for team capacity analysis.',
    data_types:  ['billable_hours', 'utilisation_rate', 'time_by_project', 'time_by_client'],
    intelligence_use_cases: [
      'Team utilisation and capacity health',
      'Billable ratio and revenue leakage',
      'Project time vs budget analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'calendly',
    name:        'Calendly',
    category:    'Ops',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull booking rate, no-shows, and scheduling patterns for capacity and pipeline diagnostics.',
    data_types:  ['bookings', 'no_shows', 'cancellation_rate', 'scheduling_patterns'],
    intelligence_use_cases: [
      'Meeting pipeline and booking conversion',
      'No-show rate and revenue leakage',
      'Scheduling capacity and bottleneck',
    ],
    required_tier: 'intelligence',
  },

  // ── Engineering ───────────────────────────────────────────────────────────────
  {
    id:          'jira',
    name:        'Jira',
    category:    'Engineering',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull sprint velocity, bug count, and open issues for engineering health diagnostics.',
    data_types:  ['sprint_velocity', 'bug_count', 'open_issues', 'cycle_time'],
    intelligence_use_cases: [
      'Sprint velocity and delivery gap',
      'Bug accumulation and tech debt signals',
      'Engineering throughput analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'linear',
    name:        'Linear',
    category:    'Engineering',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull sprint velocity, open issues, and cycle time for engineering execution analysis.',
    data_types:  ['sprint_velocity', 'open_issues', 'cycle_time', 'priorities'],
    intelligence_use_cases: [
      'Engineering velocity and throughput',
      'Issue backlog health',
      'Priority alignment vs execution',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'github',
    name:        'GitHub',
    category:    'Engineering',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull deployment frequency, PR cycle time, and open bugs for engineering health.',
    data_types:  ['deployment_frequency', 'pr_cycle_time', 'open_issues', 'bug_count'],
    intelligence_use_cases: [
      'Deployment velocity and release cadence',
      'PR review bottleneck detection',
      'Bug accumulation and tech debt signals',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'datadog',
    name:        'Datadog',
    category:    'Engineering',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull error rate, uptime, and incident frequency for system reliability diagnostics.',
    data_types:  ['error_rate', 'uptime', 'incident_count', 'latency'],
    intelligence_use_cases: [
      'System reliability and uptime monitoring',
      'Error rate trend and root cause signals',
      'Incident frequency and MTTR analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'sentry',
    name:        'Sentry',
    category:    'Engineering',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull error rate, incident frequency, and crash data for product reliability diagnostics.',
    data_types:  ['error_rate', 'crash_rate', 'incident_count', 'affected_users'],
    intelligence_use_cases: [
      'Error and crash rate trend analysis',
      'Incident frequency and resolution time',
      'User-impacting bug severity monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'freshservice',
    name:        'Freshservice',
    category:    'Engineering',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull IT ticket volume, resolution time, and SLA adherence for IT ops health diagnostics.',
    data_types:  ['ticket_volume', 'resolution_time', 'sla_adherence', 'change_requests'],
    intelligence_use_cases: [
      'IT support load and resolution efficiency',
      'SLA adherence and breach rate',
      'Change request volume and risk monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'cloudflare',
    name:        'Cloudflare',
    category:    'Engineering',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull traffic, threat data, and uptime for infrastructure and security diagnostics.',
    data_types:  ['traffic', 'threat_events', 'uptime', 'bandwidth'],
    intelligence_use_cases: [
      'Security threat and attack surface monitoring',
      'CDN performance and uptime health',
      'Traffic trend and anomaly detection',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'vercel',
    name:        'Vercel',
    category:    'Engineering',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull deployment frequency, build times, and error rate for frontend ops diagnostics.',
    data_types:  ['deployments', 'build_times', 'error_rate', 'performance_scores'],
    intelligence_use_cases: [
      'Deployment velocity and release cadence',
      'Build time trend and bottleneck detection',
      'Frontend performance and error monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'circleci',
    name:        'CircleCI',
    category:    'Engineering',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull build success rate, pipeline duration, and failure patterns for CI/CD health.',
    data_types:  ['build_success_rate', 'pipeline_duration', 'failure_patterns', 'test_results'],
    intelligence_use_cases: [
      'CI/CD pipeline health and success rate',
      'Build failure pattern detection',
      'Test coverage and reliability trend',
    ],
    required_tier: 'intelligence',
  },

  // ── E-commerce / Shipping ─────────────────────────────────────────────────────
  {
    id:          'zohoinventory',
    name:        'Zoho Inventory',
    category:    'Ecommerce',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull stock levels, fulfilment rate, and inventory turnover for operations health.',
    data_types:  ['stock_levels', 'fulfilment_rate', 'inventory_turnover', 'low_stock_alerts'],
    intelligence_use_cases: [
      'Inventory turnover and dead stock detection',
      'Fulfilment rate and stock-out risk',
      'Reorder point and demand trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'shopify',
    name:        'Shopify',
    category:    'Ecommerce',
    status:      'available',
    semantic_status: 'verified',
    auth_type:   'oauth',
    description: 'Pull GMV, orders, AOV, cart abandonment, and refund rate for commerce health.',
    data_types:  ['gmv', 'orders', 'aov', 'cart_abandonment', 'refund_rate'],
    intelligence_use_cases: [
      'GMV trend and revenue concentration risk',
      'Cart abandonment and conversion gap',
      'Refund rate and fulfilment health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'wix',
    name:        'Wix',
    category:    'Ecommerce',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull site traffic, store revenue, and order data for small business commerce diagnostics.',
    data_types:  ['traffic', 'revenue', 'orders', 'conversion_rate'],
    intelligence_use_cases: [
      'Traffic and conversion health',
      'Revenue trend and order volume',
      'Store performance benchmarking',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'shippo',
    name:        'Shippo',
    category:    'Ecommerce',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull shipping rates, delivery time, and carrier performance for fulfilment diagnostics.',
    data_types:  ['shipping_rates', 'delivery_time', 'carrier_performance', 'label_volume'],
    intelligence_use_cases: [
      'Carrier performance and delivery time analysis',
      'Shipping cost optimisation signals',
      'Fulfilment volume trend',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'shipengine',
    name:        'ShipEngine',
    category:    'Ecommerce',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull multi-carrier shipping data and delivery performance for logistics diagnostics.',
    data_types:  ['carrier_performance', 'delivery_time', 'shipping_cost', 'tracking_events'],
    intelligence_use_cases: [
      'Carrier performance benchmarking',
      'Shipping cost and efficiency analysis',
      'Delivery time trend monitoring',
    ],
    required_tier: 'intelligence',
  },

  // ── Analytics / Product ───────────────────────────────────────────────────────
  {
    id:          'mixpanel',
    name:        'Mixpanel',
    category:    'Analytics',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull DAU/MAU, activation rate, retention curves, and feature usage for product health.',
    data_types:  ['dau', 'mau', 'activation_rate', 'retention', 'feature_usage'],
    intelligence_use_cases: [
      'User activation and onboarding gap',
      'Retention curve and churn signal',
      'Feature usage and adoption analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'amplitude',
    name:        'Amplitude',
    category:    'Analytics',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull DAU/MAU, activation rate, retention, and feature usage for product diagnostics.',
    data_types:  ['dau', 'mau', 'activation_rate', 'retention_curves', 'conversion_funnels'],
    intelligence_use_cases: [
      'User retention and engagement health',
      'Activation funnel gap detection',
      'Feature adoption and stickiness analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'posthog',
    name:        'PostHog',
    category:    'Analytics',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull DAU/MAU, retention, funnels, and session data for product health diagnostics.',
    data_types:  ['dau', 'mau', 'retention', 'funnels', 'session_recordings'],
    intelligence_use_cases: [
      'Product engagement and retention health',
      'Funnel drop-off and conversion gap',
      'Feature usage and adoption monitoring',
    ],
    required_tier: 'intelligence',
  },

  // ── Legal / Contracts ─────────────────────────────────────────────────────────
  {
    id:          'docusign',
    name:        'DocuSign',
    category:    'Legal',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull contract cycle time, unsigned documents, and signature completion rate.',
    data_types:  ['contract_cycle_time', 'unsigned_docs', 'completion_rate', 'envelope_volume'],
    intelligence_use_cases: [
      'Contract bottleneck and cycle time analysis',
      'Unsigned document backlog detection',
      'Signature completion rate monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'pandadoc',
    name:        'PandaDoc',
    category:    'Legal',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull proposal win rate, document cycle time, and completion rate for sales ops health.',
    data_types:  ['proposal_win_rate', 'cycle_time', 'completion_rate', 'document_volume'],
    intelligence_use_cases: [
      'Proposal win rate and conversion analysis',
      'Document cycle time and bottleneck',
      'Sales ops efficiency monitoring',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'dropboxsign',
    name:        'Dropbox Sign',
    category:    'Legal',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull signature request status, completion rate, and cycle time for contract health.',
    data_types:  ['completion_rate', 'cycle_time', 'pending_signatures', 'declined_rate'],
    intelligence_use_cases: [
      'Contract completion rate and velocity',
      'Pending signature backlog detection',
      'Declined document pattern analysis',
    ],
    required_tier: 'intelligence',
  },

  // ── Healthcare / Scheduling ───────────────────────────────────────────────────
  {
    id:          'commcare',
    name:        'CommCare',
    category:    'Healthcare',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull patient case data, form submissions, and field worker activity for care health.',
    data_types:  ['case_volume', 'form_submissions', 'worker_activity', 'follow_up_rate'],
    intelligence_use_cases: [
      'Patient case volume and follow-up gaps',
      'Field worker activity and coverage',
      'Care delivery and outcome trend',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'jotform',
    name:        'Jotform',
    category:    'Healthcare',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull form submission rates and intake data for patient onboarding diagnostics.',
    data_types:  ['form_submissions', 'completion_rate', 'drop_off_rate'],
    intelligence_use_cases: [
      'Patient intake completion rate',
      'Form drop-off and barrier detection',
      'Intake volume trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'typeform',
    name:        'Typeform',
    category:    'Healthcare',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull survey completion rate and response data for patient experience diagnostics.',
    data_types:  ['completion_rate', 'response_rate', 'drop_off_points', 'nps'],
    intelligence_use_cases: [
      'Patient satisfaction and NPS trend',
      'Survey completion and drop-off analysis',
      'Feedback volume and response rate',
    ],
    required_tier: 'intelligence',
  },

  // ── Hospitality / Bookings ────────────────────────────────────────────────────
  {
    id:          'square',
    name:        'Square',
    category:    'Hospitality',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull revenue per day, average transaction, and sales data for retail and F&B diagnostics.',
    data_types:  ['revenue_per_day', 'avg_transaction', 'transaction_count', 'refunds'],
    intelligence_use_cases: [
      'Daily revenue trend and variance',
      'Average transaction and basket size',
      'Refund rate and customer satisfaction signal',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'lodgify',
    name:        'Lodgify',
    category:    'Hospitality',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull occupancy rate, booking revenue, and channel performance for vacation rental health.',
    data_types:  ['occupancy_rate', 'booking_revenue', 'channel_performance', 'avg_daily_rate'],
    intelligence_use_cases: [
      'Occupancy rate and revenue trend',
      'Booking channel performance analysis',
      'Average daily rate and pricing health',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'planyo',
    name:        'Planyo',
    category:    'Hospitality',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull booking rate, cancellations, and reservation volume for business capacity diagnostics.',
    data_types:  ['booking_rate', 'cancellations', 'reservation_volume', 'utilisation_rate'],
    intelligence_use_cases: [
      'Booking capacity and utilisation health',
      'Cancellation rate and revenue leakage',
      'Reservation volume trend analysis',
    ],
    required_tier: 'intelligence',
  },

  // ── Logistics / Delivery ──────────────────────────────────────────────────────
  {
    id:          'detrack',
    name:        'Detrack',
    category:    'Logistics',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull delivery completion rate, on-time performance, and driver activity for ops health.',
    data_types:  ['delivery_completion', 'on_time_rate', 'driver_activity', 'failed_deliveries'],
    intelligence_use_cases: [
      'Delivery completion and on-time rate',
      'Failed delivery pattern detection',
      'Driver productivity and route efficiency',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'optimoroute',
    name:        'OptimoRoute',
    category:    'Logistics',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull route efficiency, delivery time, and fleet utilisation for logistics diagnostics.',
    data_types:  ['route_efficiency', 'delivery_time', 'fleet_utilisation', 'stops_per_route'],
    intelligence_use_cases: [
      'Route efficiency and cost optimisation',
      'Fleet utilisation and capacity analysis',
      'Delivery time trend and variance',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'route4me',
    name:        'Route4Me',
    category:    'Logistics',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull route optimisation data and delivery performance for fleet ops diagnostics.',
    data_types:  ['route_efficiency', 'delivery_time', 'driver_performance', 'cost_per_route'],
    intelligence_use_cases: [
      'Route cost and efficiency analysis',
      'Driver performance benchmarking',
      'Delivery time and reliability monitoring',
    ],
    required_tier: 'intelligence',
  },

  // ── Media / Creator ───────────────────────────────────────────────────────────
  {
    id:          'youtubeanalytics',
    name:        'YouTube Analytics',
    category:    'Media',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull views, watch time, subscriber growth, and drop-off for audience health.',
    data_types:  ['views', 'watch_time', 'subscriber_growth', 'drop_off_rate'],
    intelligence_use_cases: [
      'Audience growth and retention analysis',
      'Watch time and engagement trend',
      'Content drop-off and hook performance',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'spotify',
    name:        'Spotify',
    category:    'Media',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull streams, listener growth, and drop-off for podcast and music audience diagnostics.',
    data_types:  ['streams', 'listeners', 'subscriber_growth', 'completion_rate'],
    intelligence_use_cases: [
      'Audience growth and listener retention',
      'Episode completion and drop-off rate',
      'Listener engagement trend analysis',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'webflow',
    name:        'Webflow',
    category:    'Media',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull site traffic, form submissions, and CMS content data for digital presence diagnostics.',
    data_types:  ['site_traffic', 'form_submissions', 'page_performance', 'cms_items'],
    intelligence_use_cases: [
      'Website traffic and conversion health',
      'Content performance and engagement',
      'Lead capture and form submission rate',
    ],
    required_tier: 'intelligence',
  },
  {
    id:          'gumroad',
    name:        'Gumroad',
    category:    'Media',
    status:      'available',
    semantic_status: 'transport-only',
    auth_type:   'oauth',
    description: 'Pull product sales, revenue, and subscriber data for creator business diagnostics.',
    data_types:  ['sales', 'revenue', 'subscribers', 'refund_rate'],
    intelligence_use_cases: [
      'Product sales and revenue trend',
      'Subscriber growth and retention',
      'Refund rate and product health signals',
    ],
    required_tier: 'intelligence',
  },
]

// Returns the full registry
export function getConnectorRegistry() {
  return CONNECTOR_REGISTRY
}

// Returns only connectors with status === 'available'
export function getAvailableConnectors() {
  return CONNECTOR_REGISTRY.filter(c => c.status === 'available')
}

// Returns connector IDs that can be used as communication push channels
export function getCommChannelProviders() {
  return CONNECTOR_REGISTRY.filter(c => c.comm_channel === true).map(c => c.id)
}

// Returns a single connector definition by id, or null
export function getConnectorDefinition(id) {
  return CONNECTOR_REGISTRY.find(c => c.id === id) ?? null
}
