export const CAPABILITY_DETAILS = {
  sentinel: {
    index: '01',
    name: 'Sentinel',
    question: 'What is breaking?',
    headline: 'The business should not have to fail loudly before you notice.',
    intro: 'Sentinel checks the operating standards you define, connects related signals across the business, and brings the issues that deserve attention to the top.',
    analogyTitle: 'Think of it as a smoke detector with an investigator attached.',
    analogy: 'A normal alert says there is smoke. Sentinel also looks for the room it started in, what it could spread to, and which fire matters first.',
    tags: ['Continuous monitoring', 'Cross-area reasoning', 'Prioritized signals'],
    flowTitle: 'From a weak signal to a decision-ready warning',
    flow: [
      { number: '01', title: 'Watch the standards', body: 'Configured metrics are checked against the targets and thresholds that define healthy operation.' },
      { number: '02', title: 'Connect the pattern', body: 'Related movement across finance, sales, service, people, and strategy is evaluated together.' },
      { number: '03', title: 'Explain the issue', body: 'The signal is summarized with the likely driver, affected area, urgency, and available evidence.' },
      { number: '04', title: 'Rank the attention', body: 'The most consequential issues rise above ordinary noise so the operator knows where to begin.' },
    ],
    exampleLabel: 'A simple example',
    exampleTitle: 'Churn rises while runway shortens.',
    exampleSetup: 'A dashboard could show two separate numbers. Sentinel treats them as one operating pattern because customer loss is now accelerating financial pressure.',
    exampleBefore: { label: 'Separate facts', value: 'Churn 6.6% · Runway 5.9 months', note: 'Useful numbers, but no shared meaning.' },
    exampleAfter: { label: 'Sentinel signal', value: 'Cash fragility is becoming critical', note: 'Likely driver, affected area, urgency, and recommended next step are shown together.' },
    truths: [
      { title: 'It uses your definition of healthy', body: 'The system does not invent a universal standard for your business. It evaluates the thresholds and operating logic configured for you.' },
      { title: 'It separates signal from missing evidence', body: 'When impact cannot be supported by available data, Sentinel says it is not quantified instead of manufacturing precision.' },
      { title: 'It advises before it acts', body: 'A finding can prepare a recommended action, but execution remains inside the approval boundary.' },
    ],
    guardrail: 'Sentinel is an early-warning and reasoning layer. It improves attention and decision speed; it does not replace source-system accuracy or operator judgment.',
    next: 'foresight',
  },
  foresight: {
    index: '02',
    name: 'Foresight',
    question: 'What happens if?',
    headline: 'Test the decision before the business has to live with it.',
    intro: 'Foresight starts from the current business position, changes one assumption, and traces the likely consequences through the relationships modeled in Origin.',
    analogyTitle: 'Think of it as a wind tunnel for business decisions.',
    analogy: 'An aircraft is tested against pressure before it flies. Foresight lets an operator apply pressure to a decision before money, customers, or runway are exposed.',
    tags: ['What-if modeling', 'Scenario comparison', 'Explicit assumptions'],
    flowTitle: 'From a proposed change to a bounded scenario',
    flow: [
      { number: '01', title: 'State the decision', body: 'Ask a concrete question such as what happens if churn reaches 7% or pipeline falls by 30%.' },
      { number: '02', title: 'Anchor the baseline', body: 'The scenario begins with the available live metrics and the current modeled business position.' },
      { number: '03', title: 'Trace the consequences', body: 'Configured dependencies carry the change into the areas it is expected to influence.' },
      { number: '04', title: 'Label the certainty', body: 'Results are separated into calculated, estimated, and directional outcomes rather than blended into false precision.' },
    ],
    exampleLabel: 'A simple example',
    exampleTitle: 'What if churn reaches 7%?',
    exampleSetup: 'Foresight does not answer with one magical number. It shows what can be calculated directly, what depends on assumptions, and where the pressure is only directional.',
    exampleBefore: { label: 'Current position', value: 'Churn 5.2% · MRR $420k', note: 'The baseline before the proposed change.' },
    exampleAfter: { label: 'Modeled consequence', value: 'Retention pressure → lower MRR → shorter runway', note: 'Each outcome carries its evidence level and assumptions.' },
    truths: [
      { title: 'Calculated means measured mathematics', body: 'Direct arithmetic from available values is shown as calculated rather than attributed to AI judgment.' },
      { title: 'Estimated means assumptions are visible', body: 'Ranges and modeled effects are presented with the assumptions required to produce them.' },
      { title: 'Directional means the sign is clearer than the size', body: 'When the model can support likely pressure but not an exact value, it says so plainly.' },
    ],
    guardrail: 'Foresight is a decision model, not a promise about the future. Its value comes from exposing consequences and assumptions before commitment.',
    next: 'counsel',
  },
  counsel: {
    index: '03',
    name: 'Counsel',
    question: 'Why is it happening?',
    headline: 'Ask the business a question without first knowing which dashboard to open.',
    intro: 'Counsel investigates the relevant connected context, separates verified facts from judgment, and returns a business answer that can be challenged and continued as a conversation.',
    analogyTitle: 'Think of it as an analyst who already has the operating model open.',
    analogy: 'You bring the question. Counsel works out which areas matter, checks the available evidence, and explains its view without making you assemble the investigation yourself.',
    tags: ['Business conversation', 'Evidence-aware answers', 'Persistent context'],
    flowTitle: 'From an open question to a grounded business view',
    flow: [
      { number: '01', title: 'Understand the intent', body: 'Counsel identifies the decision, risk, goal, or operating concern behind the question.' },
      { number: '02', title: 'Choose the context', body: 'It selects the relevant modeled areas, metrics, signals, and connected evidence automatically.' },
      { number: '03', title: 'Separate fact and judgment', body: 'Measured evidence, interpretation, uncertainty, and missing information remain distinguishable.' },
      { number: '04', title: 'Continue the investigation', body: 'The conversation remains available so the operator can challenge the answer or go deeper without restarting.' },
    ],
    exampleLabel: 'A simple example',
    exampleTitle: 'Why is pipeline losing momentum?',
    exampleSetup: 'Instead of returning a generic sales answer, Counsel can connect the question to the evidence that exists across the modeled business.',
    exampleBefore: { label: 'The question', value: 'Why are fewer opportunities advancing?', note: 'The operator does not need to specify every source to inspect.' },
    exampleAfter: { label: 'Counsel view', value: 'Lead quality weakened while the sales cycle lengthened', note: 'Supporting facts, judgment, uncertainty, and the next useful investigation remain visible.' },
    truths: [
      { title: 'The answer is only as grounded as the available context', body: 'Counsel can reason across connected evidence, but it cannot verify information the business has not supplied.' },
      { title: 'Conversation memory preserves the investigation', body: 'Past questions and answers stay organized by conversation so follow-up questions retain their working context.' },
      { title: 'External action still requires approval', body: 'Counsel can recommend or prepare work, but it does not silently reach into business systems and make changes.' },
    ],
    guardrail: 'Counsel is a reasoning interface over the modeled business. It should make uncertainty easier to see—not hide it behind confident language.',
    next: 'dispatch',
  },
  dispatch: {
    index: '04',
    name: 'Dispatch',
    question: 'Now what?',
    headline: 'Turn a decision into controlled work without losing the evidence behind it.',
    intro: 'Dispatch gathers prepared action packages from Sentinel, Counsel, Foresight, and audits, then gives the operator one place to review, approve, reject, and track them.',
    analogyTitle: 'Think of it as air traffic control for business actions.',
    analogy: 'Knowing where every aircraft should go is not enough. Someone still needs to verify the route, authorize movement, and track what actually happened.',
    tags: ['Action packages', 'Approval boundaries', 'Execution tracking'],
    flowTitle: 'From recommendation to governed execution',
    flow: [
      { number: '01', title: 'Prepare the package', body: 'The recommendation, source, evidence, intended outcome, and proposed artifact travel together.' },
      { number: '02', title: 'Review the boundary', body: 'The operator can inspect what will change, where it will go, and what still requires human approval.' },
      { number: '03', title: 'Approve or reject', body: 'Nothing crosses the approval boundary simply because the system recommended it.' },
      { number: '04', title: 'Track the state', body: 'Ready, in-progress, completed, failed, and rejected work remains visible in one governed queue.' },
    ],
    exampleLabel: 'A simple example',
    exampleTitle: 'Sentinel finds an onboarding breakdown.',
    exampleSetup: 'The diagnosis is useful, but the business still needs controlled work. Dispatch keeps the fix connected to the reason it exists.',
    exampleBefore: { label: 'Prepared package', value: 'Onboarding recovery plan', note: 'Evidence, owner, recommended steps, and approval requirement are bundled together.' },
    exampleAfter: { label: 'Governed outcome', value: 'Reviewed → approved → tracked', note: 'Supported connected actions execute only after approval; everything else remains a clear work artifact.' },
    truths: [
      { title: 'The evidence stays attached', body: 'The reviewer can see why the package exists instead of receiving an isolated task with no operating context.' },
      { title: 'Approval is an explicit state', body: 'Needs approval, ready, in progress, completed, failed, and rejected are separate operational conditions.' },
      { title: 'Execution depends on the destination', body: 'A package can always be reviewed and tracked; direct execution requires a supported and authorized connector.' },
    ],
    guardrail: 'Dispatch governs the transition from intelligence to action. It does not turn every recommendation into an automatic change.',
    next: 'sentinel',
  },
}
