create table if not exists public.foresight_runs (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model_version text not null,
  question text not null check (char_length(question) between 1 and 2000),
  status text not null check (status in ('modeled', 'bounded', 'insufficient_evidence')),
  scenario jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  baseline_observed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists foresight_runs_user_created_idx
  on public.foresight_runs (user_id, created_at desc);

alter table public.foresight_runs enable row level security;

revoke all privileges on table public.foresight_runs from anon, authenticated;
grant select on table public.foresight_runs to authenticated;
grant select, insert, delete on table public.foresight_runs to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'foresight_runs'
      and policyname = 'Users select own foresight runs'
  ) then
    create policy "Users select own foresight runs"
      on public.foresight_runs for select
      to authenticated
      using ((select auth.uid()) = user_id);
  end if;
end $$;

comment on table public.foresight_runs is
  'Immutable server-generated Foresight results used as the authority for save and Dispatch operations.';

comment on column public.foresight_runs.result is
  'Evidence-gated result generated by the server. Browser-supplied result payloads must not overwrite this value.';

revoke insert, update on table public.foresight_scenarios from authenticated;

comment on table public.foresight_scenarios is
  'User-visible saved scenarios. New rows are copied from server-owned foresight_runs by the authenticated API.';
